### ISSUE TITLE
Where is "run_synthet.sh"？

### ISSUE THREAD

**Issue by wuxingywa** [OPTML-Group/Unlearn-Simple#2]
Hi, I think this is very interesting work. 

I found that SIMNPO's README says "Please see 'run_synthetic.sh' for how to run the code."

But I can't seem to find the file "run_synthetic.sh" where?

**Comment by a-F1** [comment]
Thank you for your recognition of and interest in our work! We have uploaded the `run_synthetic.sh` script as requested.

If you have any further questions, please don't hesitate to reach out to us!

**Comment by a-F1** [comment]
The issue has been closed. If you have any further questions, feel free to contact us at any time.
