### ISSUE TITLE
About training and experiment costs

### ISSUE THREAD

**Issue by suiyize** [OPTML-Group/Unlearn-Simple#3]
Very interesting work. I would like to ask how much GPU resources and time are spent in training and experiments? It doesn't seem to be mentioned in the paper.

**Comment by a-F1** [comment]
Thank you for your interest and attention to our work. You can find the details in Appendix C.2.

If you have any further questions, feel free to reach out to us.

**Comment by a-F1** [comment]
The issue has been closed. If you have any other questions, please feel free to reach out to us.
