### ISSUE TITLE
About reward margin parameter γ

### ISSUE THREAD

**Issue by suiyize** [OPTML-Group/Unlearn-Simple#4]
Hi, I had some theoretical questions while reading SimPO,NPO and your work (SimNPO).

In NPO, they treat unlearning problem as a preference optimization problem that only provides negative response yl and ignores positive response yw.

In SimPO, the target reward margin γ they introduced is essentially that the reward r(x, yw) for winning the response exceeds the reward r(x, yl) for losing the response.

Your work is similar to SimPO's idea of not introducing a reference model but introducing a reward margin parameter γ.

But at this point the positive response yw has been ignored, why are you still able to construct a reward margin parameter γ?

**Comment by a-F1** [comment]
Thank you for your attention and interest in our work. Both NPO and SimNPO essentially perform unlearning through preference optimization, focusing only on negative samples during the process. You can interpret 𝛾 as the margin of preference for a desired response over a dispreferred one. A larger 𝛾 provides greater compensation to further suppress token prediction, enforcing a stricter unlearning condition. More discussion on 𝛾 and 𝛽 can be found in Fig. A1.

Please feel free to contact me if you have any further questions.

**Comment by a-F1** [comment]
The issue has been closed. If you have any further questions, feel free to contact us at any time.

**Comment by a-F1** [comment]
The issue has been closed. If you have any other questions, please feel free to reach out to us.
